### ISSUE TITLE
PMlock does not work with "cut" - intentional?

### ISSUE THREAD

**Issue by muenger** [Falke-Design/PMLock#14]
Thanks for this excellent and extremely helpful subplugin to geoman! I noticed, however, that this does not work when one is using the "cut-tool". Is this intentional? -- I would highly welcome that also "cut" is not possible with locked layers. Thanks again for this great addition to geoman!

**Comment by Falke-Design** [comment]
Implemented in Leaflet-Geoman with [Release 2.11.0](https://github.com/geoman-io/leaflet-geoman/releases/tag/2.11.0). This Library will not longer supported
